# Generated by Django 5.2.6 on 2026-07-27 12:37

import django.db.models.deletion
import documentos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundos', '0006_fundo_limite_direitos_creditorios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFundo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('LAUDO_PRECIFICACAO', 'Laudo de Precificação'), ('LAUDO_AVALIACAO', 'Laudo de Avaliação'), ('CONTRATO_CESSAO', 'Contratos de Cessão'), ('LASTRO', 'Lastros'), ('ATA_COMITE', 'Atas de Comitê')], db_index=True, max_length=30)),
                ('arquivo', models.FileField(max_length=500, upload_to=documentos.models.upload_documento_path)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('tamanho', models.PositiveBigIntegerField(default=0, help_text='Tamanho do arquivo em bytes')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Documento do Fundo',
                'verbose_name_plural': 'Documentos do Fundo',
                'db_table': 'documentos_fundo',
                'ordering': ['-data_upload'],
                'indexes': [models.Index(fields=['fundo', 'categoria'], name='documentos__fundo_i_038b92_idx')],
            },
        ),
    ]
