# Generated by Django 5.2.6 on 2026-06-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0002_add_informe_mensal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='administrador',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fundo',
            name='aporte_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundo',
            name='auditoria',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fundo',
            name='condicoes_resgate',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='fundo',
            name='data_encerramento_exercicio',
            field=models.CharField(blank=True, help_text='Ex: 31/12', max_length=10),
        ),
        migrations.AddField(
            model_name='fundo',
            name='gestor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fundo',
            name='taxa_performance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
