# Generated by Django 5.2.6 on 2026-06-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0003_fundo_administrador_fundo_aporte_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo',
            name='taxa_administracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='taxa_gestao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='taxa_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
