# Generated by Django 4.2.23 on 2026-06-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0004_alter_fundo_taxa_administracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundo',
            name='auditoria',
        ),
        migrations.AddField(
            model_name='fundo',
            name='classificacao_investidor',
            field=models.CharField(blank=True, choices=[('PROFISSIONAL', 'Profissional'), ('QUALIFICADO', 'Qualificado')], max_length=20),
        ),
        migrations.AddField(
            model_name='fundo',
            name='estrutura_fundo',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], max_length=10),
        ),
        migrations.AddField(
            model_name='fundo',
            name='limite_concentracao',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='fundo',
            name='taxa_administracao_minima',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fundo',
            name='taxa_gestao_minima',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fundo',
            name='taxa_performance_minima',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fundo',
            name='tipo_condominio',
            field=models.CharField(blank=True, choices=[('PADRONIZADO', 'Padronizado'), ('NAO_PADRONIZADO', 'Não Padronizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='taxa_administracao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='taxa_gestao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='taxa_performance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
