# Generated by Django 4.2.23 on 2026-07-20 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0005_adiciona_campos_fundo_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='limite_direitos_creditorios',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Limite máximo em Direitos Creditórios (Cessões), em % da carteira', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='fundo',
            name='limite_liquidez',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Limite máximo em Liquidez (Aplicações), em % da carteira', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
