# Generated by Django 4.2.23 on 2026-07-27 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0006_fundo_limite_direitos_creditorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='limite_concentracao_devedor',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Limite máximo por devedor/cessão individual, em % da carteira', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='classificacao_investidor',
            field=models.CharField(blank=True, choices=[('PROFISSIONAL', 'Profissional'), ('QUALIFICADO', 'Qualificado'), ('VAREJO', 'Varejo')], max_length=20),
        ),
    ]
