# Generated by Django 4.2.23 on 2026-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0006_fundo_limite_direitos_creditorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='codigo_originador_cnab',
            field=models.CharField(blank=True, default='', help_text='Código originador (CDO) usado no header do arquivo de remessa CNAB deste fundo', max_length=20),
        ),
        migrations.AddField(
            model_name='fundo',
            name='ocorrencia_cnab_padrao',
            field=models.CharField(blank=True, default='01', help_text='Código de ocorrência padrão usado nas linhas de detalhe do CNAB (ex: 01 - Remessa)', max_length=2),
        ),
    ]
