# Generated by Django 4.2.23 on 2026-07-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0007_fundo_codigo_originador_cnab_and_more'),
        ('fundos', '0007_fundo_limite_concentracao_devedor_and_more'),
    ]

    operations = [
    ]
