# Generated by Django 4.2.23 on 2026-09-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0008_merge_20260727_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='coobrigacao_cnab_padrao',
            field=models.CharField(blank=True, default='02', help_text='Coobrigação padrão das linhas de detalhe do CNAB (01 - Com coobrigação, 02 - Sem coobrigação). A macro legada sempre enviou 02.', max_length=2),
        ),
    ]
