# Generated by Django 5.2.6 on 2026-07-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_add_informe_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresarole',
            name='pode_gerenciar_documentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresarole',
            name='pode_ver_documentos',
            field=models.BooleanField(default=True),
        ),
    ]
