# Generated by Django 5.2.6 on 2026-09-11 18:54

from django.db import migrations, models

DEFAULT_ANTIGO = "users/profile/default.png"


def limpar_default_inexistente(apps, schema_editor):
    """O default antigo apontava para um arquivo que nunca existiu em media/.

    Enquanto a coluna guardar essa string o campo é "truthy" e o template
    renderiza um <img> quebrado em vez do círculo de iniciais.
    """
    CustomUser = apps.get_model("usuarios", "CustomUser")
    CustomUser.objects.filter(profile_image=DEFAULT_ANTIGO).update(profile_image="")


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empresarole_pode_gerenciar_documentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/'),
        ),
        migrations.RunPython(limpar_default_inexistente, migrations.RunPython.noop),
    ]
