# Generated by Django 5.2.6 on 2026-05-25 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundos', '0002_add_informe_mensal_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoCessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedente_cnpj', models.CharField(db_index=True, max_length=18)),
                ('cedente_nome', models.CharField(max_length=200)),
                ('cedente_endereco', models.TextField(blank=True)),
                ('numero_contrato', models.CharField(db_index=True, max_length=50, unique=True)),
                ('data_contrato', models.DateField()),
                ('data_aquisicao', models.DateField(help_text='Data de aquisição dos títulos pelo fundo')),
                ('valor_total_nominal', models.DecimalField(decimal_places=2, help_text='Soma dos valores nominais dos títulos', max_digits=16)),
                ('valor_total_aquisicao', models.DecimalField(decimal_places=2, help_text='Valor pago pelo fundo na aquisição', max_digits=16)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_cessao', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Operação de Cessão',
                'verbose_name_plural': 'Operações de Cessão',
                'db_table': 'operacoes_cessao',
                'ordering': ['-data_aquisicao'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_titulo', models.CharField(db_index=True, max_length=100)),
                ('sacado_nome', models.CharField(max_length=200)),
                ('sacado_cpf_cnpj', models.CharField(db_index=True, max_length=18)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, help_text='Valor pago pelo fundo', max_digits=16)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(db_index=True)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, help_text='Atualizado conforme eventos de liquidação', max_digits=16)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='False se título foi baixado/liquidado totalmente')),
                ('percentual_pdd', models.DecimalField(decimal_places=2, default=0, help_text='Calculado conforme Resolução CMN 2682', max_digits=5)),
                ('valor_pdd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('classificacao_risco', models.CharField(choices=[('AA', 'AA - 0 dias'), ('A', 'A - 15-30 dias'), ('B', 'B - 31-60 dias'), ('C', 'C - 61-90 dias'), ('D', 'D - 91-120 dias'), ('E', 'E - 121-150 dias'), ('F', 'F - 151-180 dias'), ('G', 'G - 181-360 dias'), ('H', 'H - > 360 dias')], default='AA', max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fundo', models.ForeignKey(help_text='Redundância controlada para queries eficientes', on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='fundos.fundo')),
                ('operacao_cessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='operacoes.operacaocessao')),
            ],
            options={
                'verbose_name': 'Título (Recebível)',
                'verbose_name_plural': 'Títulos (Recebíveis)',
                'db_table': 'operacoes_titulo',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='EventoTitulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.IntegerField(choices=[(1, 'Aquisição de Título'), (2, 'Baixa de Título'), (14, 'Liquidação Parcial'), (6, 'Liquidação Total'), (10, 'Prorrogação de Vencimento'), (31, 'Ajuste de Valor'), (99, 'Reativação de Título'), (50, 'Substituição de Título'), (60, 'Protesto')], db_index=True)),
                ('data_evento', models.DateField(db_index=True)),
                ('valor_evento', models.DecimalField(blank=True, decimal_places=2, help_text='Valor relacionado (ex: valor liquidado, ajustado)', max_digits=16, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('documento_referencia', models.CharField(blank=True, help_text='Número de documento/comprovante', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_titulo', to=settings.AUTH_USER_MODEL)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operacoes.titulo')),
            ],
            options={
                'verbose_name': 'Evento de Título',
                'verbose_name_plural': 'Eventos de Título',
                'db_table': 'operacoes_evento_titulo',
                'ordering': ['-data_evento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_aplicacao', models.CharField(choices=[('TESOURO', 'Tesouro Direto'), ('COTA_FUNDO', 'Cota de Fundo'), ('COMPROMISSADA', 'Operação Compromissada'), ('OUTROS', 'Outros')], db_index=True, max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('data_aplicacao', models.DateField(db_index=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_ativo', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Aplicação em Ativo',
                'verbose_name_plural': 'Aplicações em Ativos',
                'db_table': 'operacoes_aplicacao',
                'ordering': ['-data_aplicacao'],
                'indexes': [models.Index(fields=['fundo', 'tipo_aplicacao'], name='operacoes_a_fundo_i_57ea5d_idx'), models.Index(fields=['tipo_aplicacao'], name='operacoes_a_tipo_ap_0dd1b2_idx'), models.Index(fields=['data_aplicacao'], name='operacoes_a_data_ap_db434b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='operacaocessao',
            index=models.Index(fields=['fundo', 'status'], name='operacoes_c_fundo_i_a7ec6d_idx'),
        ),
        migrations.AddIndex(
            model_name='operacaocessao',
            index=models.Index(fields=['cedente_cnpj'], name='operacoes_c_cedente_9f504c_idx'),
        ),
        migrations.AddIndex(
            model_name='operacaocessao',
            index=models.Index(fields=['data_aquisicao'], name='operacoes_c_data_aq_70355d_idx'),
        ),
        migrations.AddIndex(
            model_name='titulo',
            index=models.Index(fields=['fundo', 'ativo'], name='operacoes_t_fundo_i_88b807_idx'),
        ),
        migrations.AddIndex(
            model_name='titulo',
            index=models.Index(fields=['sacado_cpf_cnpj'], name='operacoes_t_sacado__205523_idx'),
        ),
        migrations.AddIndex(
            model_name='titulo',
            index=models.Index(fields=['data_vencimento', 'ativo'], name='operacoes_t_data_ve_23685f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventotitulo',
            index=models.Index(fields=['titulo', 'tipo_evento'], name='operacoes_e_titulo__ebbed6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventotitulo',
            index=models.Index(fields=['data_evento'], name='operacoes_e_data_ev_a7601a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventotitulo',
            index=models.Index(fields=['tipo_evento'], name='operacoes_e_tipo_ev_5c61e7_idx'),
        ),
    ]
