# Generated by Django 5.2.6 on 2026-05-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='chave_nfe',
            field=models.CharField(blank=True, default='', help_text='Chave de acesso da NF-e (44 dígitos)', max_length=44),
        ),
        migrations.AddField(
            model_name='titulo',
            name='sacado_cep',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='titulo',
            name='sacado_endereco',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
