# Generated by Django 4.2.23 on 2026-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_add_sacado_details_and_chave_nfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='coobrigacao',
            field=models.CharField(default='01', help_text='Coobrigação para CNAB (01=Com coobrigação, 02=Sem coobrigação)', max_length=2),
        ),
        migrations.AddField(
            model_name='titulo',
            name='tipo_titulo',
            field=models.CharField(default='01', help_text='Tipo do título para CNAB (01=Duplicata Mercantil, 02=Duplicata Serviços, 03=NP, etc.)', max_length=2),
        ),
    ]
