# Generated by Django 5.2.6 on 2026-07-20 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0005_adiciona_campos_fundo_v2'),
        ('operacoes', '0003_titulo_coobrigacao_titulo_tipo_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='data_liquidacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='liquidado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes_liquidadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('LIQUIDADA', 'Liquidada')], db_index=True, default='ATIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='valor_resgate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor recebido na liquidação/resgate da aplicação', max_digits=16, null=True),
        ),
        migrations.AddIndex(
            model_name='aplicacao',
            index=models.Index(fields=['status'], name='operacoes_a_status_0e00cf_idx'),
        ),
    ]
