# Generated by Django 4.2.23 on 2026-08-31 16:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_aplicacao_data_liquidacao_aplicacao_liquidado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocessao',
            name='taxa_desconto',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Taxa de desconto em % aplicada sobre o valor nominal para obter o valor presente', max_digits=7),
        ),
        migrations.AlterField(
            model_name='operacaocessao',
            name='valor_total_aquisicao',
            field=models.DecimalField(decimal_places=2, help_text='Valor presente total (soma dos valores nominais descontados pela taxa_desconto)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='valor_aquisicao',
            field=models.DecimalField(decimal_places=2, help_text='Valor presente do título: valor nominal descontado pela taxa_desconto da operação', max_digits=16),
        ),
    ]
