# Generated by Django 4.2.23 on 2026-09-08 21:53

from decimal import Decimal
from django.db import migrations, models


def limpar_coobrigacao_default_antiga(apps, schema_editor):
    """`Titulo.coobrigacao` nasceu com default '01' (com coobrigação), mas a
    macro legada sempre enviou '02' e ninguém nunca escolheu esse valor na
    tela — o '01' é só o default do modelo aparecendo nos dados.

    Em vez de sobrescrever com '02' (o que inventaria uma decisão que nunca
    foi tomada), marcamos como "não informado" (''), e o CNAB passa a cair no
    `Fundo.coobrigacao_cnab_padrao`. Só toca as linhas que estão exatamente
    no default antigo: um '02' escolhido de propósito fica intacto.
    """
    Titulo = apps.get_model('operacoes', 'Titulo')
    Titulo.objects.filter(coobrigacao='01').update(coobrigacao='')


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_add_taxa_desconto_cessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocessao',
            name='taxa_iof',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='IOF em % descontado do valor bruto da duplicata para obter o valor nominal', max_digits=7),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='coobrigacao',
            field=models.CharField(blank=True, default='', help_text='Coobrigação para CNAB (01=Com coobrigação, 02=Sem coobrigação). Vazio = não informado: o CNAB cai no coobrigacao_cnab_padrao do fundo.', max_length=2),
        ),
        migrations.RunPython(
            limpar_coobrigacao_default_antiga,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
